### ISSUE TITLE
Implement Package Directory (website)

### ISSUE THREAD

**Issue by mitra28** [mitra28/VJAM#38]

**Comment by daloopy** [comment]
Steps:
1. create an api call from server to frontend
2. create package object 
3. show package objects on website

**Comment by mitra28** [comment]
Branch "38-implement-package-directory" has been changed to "39-implement-package-upload-and-rate" and linked to issue #39. Need to create a new branch for this issue

**Comment by mitra28** [comment]
@WahabAkanbi's first step - looking into sql database
